# This file should contain everything to configure the workflow on a global scale.
# It should be complemented by a samples.tsv file that contains one row per sample.
# The units.tsv file should contain the location of each project folder
# (containing fastq files).

# -- 1. Samples configuration -- #
samples: "config/samples.tsv"
units: "config/units.tsv"
out: "/data/gpfs-1/users/cofu10_c/scratch/P1813_2nd/out"
log: "/data/gpfs-1/users/cofu10_c/scratch/P1813_2nd/log" 

# -- 2. Program configuration -- # Configure the correspondent environmental modules and program paths for version control
envmodules:
    cellranger: "/fast/groups/ag_ludwig/Modules/modulefiles/cellranger-atac/2.1.0"

# -- 3. Analysis parameters -- #
# --- a. QC --- #
fastq_screen:
      enabled: False
      index_dir: "/data/gpfs-1/users/cofu10_c/scratch/P1813/fastq_indexes"
multiqc: "--config config/multiqc_config.yaml"

# --- b. Alignment --- #
cellranger:
    reference: "/data/gpfs-1/groups/ag_ludwig/work/genome_ref/refdata-cellranger-arc-GRCh38-2020-mtMask"

# --- c. Doublet identification --- #
amulet:
    autosomes: "/data/gpfs-1/groups/ag_ludwig/work/software/AMULET/human_autosomes.txt"
    blacklist: "/data/gpfs-1/groups/ag_ludwig/work/genome_ref/ENCODE_blacklist/GRCh38_unified_blacklist.bed"

# --- d. (optional) Mitochondrial variant identification --- #
mgatk:
   enable: TRUE 

# --- e. Sample INTEGRATION and pre-processing --- #
signac:
  min_peak_width: 20
  max_peak_width: 10000
  min_counts: 500
  max_nucleosome_signal: 2
  min_TSS: 2
  min_peak_fragment: 1000
  max_peak_fragment: 30000
  min_percentage_peaks: 30
  mito:
    min_depth: 10
    min_strand_cor: 0.65
    min_cell_var: 5
    min_VMR: 0.01

# --- f. (optional) Genotyping with gotcha --- #
gotcha:
  enable: FALSE
  whitelist: "/data/gpfs-1/users/cofu10_c/work/references/barcodes/737K-cratac-v1.txt"
  primer:
    primer_sequence: "AAAGCCTGTAGTTTTACTTACTCTCGTCTCCACAG"
    reverse_complement: TRUE
    max_mismatch: 3
  mutation:
    read: "R2"
    start: 35
    end: 38
    mut_sequence: "AAA"
    wt_sequence: "ACA"

# -- Cluster resources configuration -- #
resources:
    default:
        threads: 1
        mem_mb: 8000
        walltime: 480
    fastqc:
      threads: 4
      mem_mb: 32000
    fastq_screen:
      threads: 8
    cellranger:
        threads: 4
        mem_mb: 120000
        walltime: 4320
    mgatk:
        threads: 4
        mem_mb: 64000
        walltime: 1140
    amulet:
        threads: 4
        mem_mb: 64000
        walltime: 1140
    gotcha:
        threads: 4
        mem_mb: 80000
